spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 9517538426
    driver-class-name: com.mysql.cj.jdbc.Driver